@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jun 18 17:13:41 +0800 2024
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim sim_top_behav -key {Behavioral:sim_1:Functional:sim_top} -tclbatch sim_top.tcl -protoinst "protoinst_files/bd_2c0a.protoinst" -protoinst "protoinst_files/axi_ddr_mpsoc.protoinst" -protoinst "protoinst_files/verify_write_read.protoinst" -view E:/project_fpga/ddr_write_read/sim_top_behav.wcfg -log simulate.log"
call xsim  sim_top_behav -key {Behavioral:sim_1:Functional:sim_top} -tclbatch sim_top.tcl -protoinst "protoinst_files/bd_2c0a.protoinst" -protoinst "protoinst_files/axi_ddr_mpsoc.protoinst" -protoinst "protoinst_files/verify_write_read.protoinst" -view E:/project_fpga/ddr_write_read/sim_top_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
