# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/project_fpga/ddr_write_read/ddr_write_read.srcs/sources_1/bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0.xci
# IP: The module: 'axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project_fpga/ddr_write_read/ddr_write_read.gen/sources_1/bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/project_fpga/ddr_write_read/ddr_write_read.gen/sources_1/bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/project_fpga/ddr_write_read/ddr_write_read.gen/sources_1/bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/project_fpga/ddr_write_read/ddr_write_read.srcs/sources_1/bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0.xci
# IP: The module: 'axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project_fpga/ddr_write_read/ddr_write_read.gen/sources_1/bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/project_fpga/ddr_write_read/ddr_write_read.gen/sources_1/bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/project_fpga/ddr_write_read/ddr_write_read.gen/sources_1/bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
