# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/sys.xdc

# Block Designs: bd/axi_ddr_mpsoc/axi_ddr_mpsoc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ddr_mpsoc || ORIG_REF_NAME==axi_ddr_mpsoc} -quiet] -quiet

# IP: bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_zynq_ultra_ps_e_0_0/axi_ddr_mpsoc_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ddr_mpsoc_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==axi_ddr_mpsoc_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_util_vector_logic_0_0/axi_ddr_mpsoc_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ddr_mpsoc_util_vector_logic_0_0 || ORIG_REF_NAME==axi_ddr_mpsoc_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_proc_sys_reset_0_0/axi_ddr_mpsoc_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ddr_mpsoc_proc_sys_reset_0_0 || ORIG_REF_NAME==axi_ddr_mpsoc_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_system_ila_0_0/axi_ddr_mpsoc_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ddr_mpsoc_system_ila_0_0 || ORIG_REF_NAME==axi_ddr_mpsoc_system_ila_0_0} -quiet] -quiet

# IP: bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0/axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0 || ORIG_REF_NAME==axi_ddr_mpsoc_rst_axi_m_aclk_300M_100M_0} -quiet] -quiet

# IP: bd/axi_ddr_mpsoc/ip/axi_ddr_mpsoc_PL_DDR_v1_0_0_0/axi_ddr_mpsoc_PL_DDR_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ddr_mpsoc_PL_DDR_v1_0_0_0 || ORIG_REF_NAME==axi_ddr_mpsoc_PL_DDR_v1_0_0_0} -quiet] -quiet

# XDC: e:/project_fpga/ddr_write_read/ddr_write_read.gen/sources_1/bd/axi_ddr_mpsoc/axi_ddr_mpsoc_ooc.xdc
